sudo: false
language: ruby
cache:
  bundler: true
  directories:
    - $HOME/bin

rvm:
  - 2.6.9
env:
  global:
    - TRAVIS_NODE_VERSION="12"
    - secure: "qHqOv7/skf7H5+UZrZON5mutDAzr3iI3nD1td84xu72saj42PEMqzYb98MAmAJs9soNLTlXkXitw9PHgA4PNPawBxqwKmu6c0Yoi/aevBJCUiX/SmoRAW1VB/NmmPayU5T/EC+a/YRQ8n2AHQh3UpEb5j7USSFTC2u69yCDbgOgGIwnOqtmPBmvesDN3ZiOlskMGgVrVQnTe07hdNJTiLfwpHBXu0OcvG+n7S6cPSuJ2+CFC55gOyLiLWEgl26SkAEO37ozwAM0SS8vlPzWRGXuHlmUJ1Qy3b3ILDx7/8nnEg+ziih9tHNLIOX50aUpEq5hqpOQvY28eJNORTQflRJKTx81Q1nii07VORSaACH7TL+I437aYvT57Z08j6KYjPkhHxUvLLSWEtJOJMQI5kfY+Yrv7WoaOQSj8GKt8D72pRE1t+PIt58zY2iaEcvqp1JKrLAY0PKlzKWey1NPaO1cV0ICjzpPdoElGrtoyOdyvz9PLVitcNrzo5I61urOPZKXaQzvixV8ywQ5GvVOzKPaYVsTkqDMRo/HS/R12k2X+a2iVdl3gyNTsSv3JbLH1KC4ur9PGMPDQRjBsVfFItrGPvnlvhc427gIdizEPR+TVDnXE23WE4JrwPv7bAd1vFl/B6Zfsm2L32KSlmVx9ygfNfg5ZMe+lm4bts3Tv1XE="

before_install:
  - mkdir -p "$HOME/bin"
  - export PATH="$HOME/bin:$PATH"
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem install bundler:1.15.3

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install
  - bundle install --path vendor/bundle

script:
  - "./bin/middleman build"

branches:
  only:
    - master

deploy:
  skip_cleanup: true
  provider: script
  script: ./bin/deploy.sh
  on:
    branch: master

notifications:
  email: false
